version: '3'
services:
  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://sit722part4database_user:oixNr1maKIzLcfk1qperGpCRvFAeNxrs@dpg-crnojle8ii6s73eu71bg-a.oregon-postgres.render.com/sit722part4database
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://sit722part4database_user:oixNr1maKIzLcfk1qperGpCRvFAeNxrs@dpg-crnojle8ii6s73eu71bg-a.oregon-postgres.render.com/sit722part4database
    restart: "no"
